//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGJENSITE
    {
        public long ID { get; set; }
        public string KODI { get; set; }
        public string EMRI { get; set; }
        public long KODI_POSTAR_ID { get; set; }
        public string ADRESA { get; set; }
        public string TEL { get; set; }
        public Nullable<long> SHOQERIA_ID { get; set; }
        public Nullable<long> SHOQERI_AGJENTE_ID { get; set; }
        public bool PARTNER { get; set; }
        public bool AKTIVE { get; set; }
        public string NIPT { get; set; }
    }
}
