//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANTAT
    {
        public long ID { get; set; }
        public string KODI { get; set; }
        public long AGJENSIA_SOURCE_ID { get; set; }
        public System.DateTime DATE_RREGJISTRIMI { get; set; }
        public long PERDORUES_ID { get; set; }
        public string PESHA { get; set; }
        public string NR_RRIPI_SIGURIMI { get; set; }
        public long CANTA_STATUS_ID { get; set; }
    }
}
