//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANTA_PODE
    {
        public long ID { get; set; }
        public long CANTA_ID { get; set; }
        public Nullable<long> POD_ITEM_ID { get; set; }
        public long PERDORUES_ID { get; set; }
        public System.DateTime DATE_RREGJISTRIMI { get; set; }
    }
}
