//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Group6DBEntities : DbContext
    {
        public Group6DBEntities()
            : base("name=Group6DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGJENSITE> AGJENSITEs { get; set; }
        public virtual DbSet<PERDORUE> PERDORUES { get; set; }
        public virtual DbSet<TERMINAL_PERDORUES> TERMINAL_PERDORUES { get; set; }
        public virtual DbSet<TERMINALE> TERMINALEs { get; set; }
        public virtual DbSet<Token_AGJ> Token_AGJ { get; set; }
        public virtual DbSet<KORRIERET> KORRIERETs { get; set; }
        public virtual DbSet<POD> PODs { get; set; }
        public virtual DbSet<QYTETE> QYTETEs { get; set; }
        public virtual DbSet<SHTETE> SHTETEs { get; set; }
    }
}
