//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gjenero_Cante_Pod
    {
        public int Id { get; set; }
        public string Shkronja { get; set; }
        public Nullable<int> Numra { get; set; }
        public string NumraTrue { get; set; }
    }
}
