//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class KORRIERET
    {
        public long ID { get; set; }
        public string KODI { get; set; }
        public string EMRI { get; set; }
        public string MBIEMRI { get; set; }
        public bool AKTIV { get; set; }
        public System.DateTime DATE_RREGJISTRIMI { get; set; }
        public long AGJENSIA_ID { get; set; }
        public long TIPI_PUNONJESI_ID { get; set; }
    }
}
