//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class KURSI
    {
        public long ID { get; set; }
        public long MONEDHA_SOURCE_ID { get; set; }
        public long MONEDHA_DESTINACION_ID { get; set; }
        public string VEPRIMI { get; set; }
        public string KURSI1 { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public string ModifiedBY { get; set; }
        public string KURSI_BF_CH { get; set; }
    }
}
