//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEVIZJA_DREJTIM
    {
        public long Id { get; set; }
        public string LEVIZJA { get; set; }
        public string DREJTIM { get; set; }
    }
}
