//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERDORUE
    {
        public long ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public bool AKTIVE { get; set; }
        public Nullable<long> KlienteSubjekteId { get; set; }
        public Nullable<long> RoleID { get; set; }
    }
}
