//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERQINDJE_KLIENTE_SUBJEKTE
    {
        public long ID { get; set; }
        public long KLIENTE_SUBJEKTE_ID { get; set; }
        public string PERQINDJE_DISCOUNT { get; set; }
        public System.DateTime DATE_RREGJISTRIMI { get; set; }
        public string KODI_LEVIZJES { get; set; }
        public string KODI_SHERBIMIT { get; set; }
        public string AKTIVE { get; set; }
        public long UPDATED_BY_ID { get; set; }
    }
}
