//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class POD_ORDERS
    {
        public long ID { get; set; }
        public string KODI { get; set; }
        public long AGJENSIA_ORIGJINE_ID { get; set; }
        public Nullable<long> QYTETI_DESTINACION_ID { get; set; }
        public Nullable<long> KORRIERI_ID { get; set; }
        public long KODI_PRODUKTI_ID { get; set; }
        public string COPE { get; set; }
        public string PESHA { get; set; }
        public string PESHA_VOLUMETRIKE { get; set; }
        public System.DateTime DATA { get; set; }
        public string PERSHKRIMI { get; set; }
        public string DER_EMRI { get; set; }
        public string DER_MBIEMRI { get; set; }
        public string DER_ADRESA { get; set; }
        public long DER_QYTETI_ID { get; set; }
        public long DER_SHTETI_ID { get; set; }
        public string DER_TEL { get; set; }
        public long DER_KODI_POSTAR_ID { get; set; }
        public string MAR_EMRI { get; set; }
        public string MAR_MBIEMRI { get; set; }
        public string MAR_ADRESA { get; set; }
        public Nullable<long> MAR_QYTETI_ID { get; set; }
        public Nullable<long> MAR_SHTETI_ID { get; set; }
        public string MAR_TEL { get; set; }
        public Nullable<long> MAR_KODI_POSTAR_ID { get; set; }
        public string CMIMI_BAZE { get; set; }
        public string SHTESA { get; set; }
        public string TVSH { get; set; }
        public string SHUMA_SHERBIME_EXTRA { get; set; }
        public Nullable<long> MENYRA_PAGESES_ID { get; set; }
        public Nullable<bool> PAGUESI_DERGUES_MARRES { get; set; }
        public string SHERBIME_EXTRA { get; set; }
        public Nullable<long> SHERBIME_EXTRA_MENYRE_PAGESE_ID { get; set; }
        public Nullable<long> DER_SUBJ_ID { get; set; }
        public Nullable<long> MARR_SUBJ_ID { get; set; }
        public Nullable<System.DateTime> DATE_RREGJISTRIMI { get; set; }
        public Nullable<long> PERDORUES_ID { get; set; }
        public string NUMRI_CEK { get; set; }
        public Nullable<long> MONEDHA_EXTRA_ID { get; set; }
        public Nullable<long> POD_STATUS_ID { get; set; }
        public Nullable<long> BANKA_ID { get; set; }
        public Nullable<bool> SIGURUAR { get; set; }
        public string VLERA_SIGURUAR { get; set; }
        public string KODI_POSTAR_MARRES { get; set; }
        public string VLERA_JASHTE_ZONE { get; set; }
        public Nullable<long> KODI_PERSHKRIMIT_ID { get; set; }
        public Nullable<long> MONEDHA_CMIMI_BAZE_ID { get; set; }
        public string PERQINDJE_DISCOUNT { get; set; }
        public string KURSI_CMIMI_BAZE { get; set; }
        public string CMIMI_BAZE_EURO { get; set; }
        public string KODI_LEVIZJES { get; set; }
        public string PERQINDJE_TVSH { get; set; }
        public Nullable<long> AGJENSIA_DEST_PIKE_PIKE_ID { get; set; }
        public Nullable<long> AGJENSIA_REMOTE_ID { get; set; }
        public string TERMINAL_PROCESSOR_ID { get; set; }
        public string TERMINAL_SERIAL_BIOS { get; set; }
        public Nullable<long> AGJENSIA_DESTINACION_ID { get; set; }
        public string KODI_SHERBIMIT { get; set; }
        public string PERQINDJE_TAKSE_KARBURANTI { get; set; }
        public string TAKSE_KARBURANTI_VALUE_LEK { get; set; }
        public string TAKSE_KARBURANTI_VALUE_EURO { get; set; }
        public string KODI_REFERENCE { get; set; }
        public string TVSH_SHTESA { get; set; }
        public string TVSH_VL_SIGURUAR { get; set; }
        public string TVSH_CMIMI_BAZE { get; set; }
        public string CMIMI_ZBRITJE { get; set; }
        public Nullable<long> DERGUES_KUNDREJT_PAGESE_ID { get; set; }
        public string STATUSI { get; set; }
        public Nullable<System.DateTime> DATA_SKANIMI { get; set; }
        public Nullable<long> ZONA_ID { get; set; }
        public string KOMENTE_SHTESE { get; set; }
        public string KOMENTE_STATUS { get; set; }
        public string NJESI_ADMINISTRATIVE { get; set; }
        public Nullable<long> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
        public string KOD_POSTAR { get; set; }
        public Nullable<long> FSHAT_ID { get; set; }
        public Nullable<long> QYTET_ID_NEW { get; set; }
        public Nullable<long> BRAND_ID { get; set; }
        public Nullable<long> DREJTIM_ID { get; set; }
        public Nullable<long> AGJENSI_TRANZIT { get; set; }
        public string LLOJ_PRODUKTI { get; set; }
        public Nullable<long> AKSI_ID { get; set; }
        public Nullable<bool> KONFIRMIM { get; set; }
    }
}
