//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERMINALE
    {
        public long ID { get; set; }
        public string ID_PROCESORI { get; set; }
        public string SERIAL_BIOS { get; set; }
        public Nullable<bool> AKTIVE { get; set; }
        public Nullable<long> AGJENSIA_ID { get; set; }
    }
}
