//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVSH
    {
        public long ID { get; set; }
        public string PERQINDJE { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string AKTIVE { get; set; }
    }
}
